### PR TITLE
Add docker compose example demo

### LINKED ISSUE #82: Feature: Add docker compose example
### Is your feature request related to a problem? Please describe.

It will be handy to add a docker-compose example as we will be able to showcase how the users could run this in a simulated multithreaded setup, eg. running multiple instances of the `datagen` script to increase the throughput

### PR DESCRIPTION
**Pull request by bobbyiliev**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [x] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Adding a docker compose example demo that will allow users to run multiple instances of the `datagen` simultaneously. 

Also moving the e-commerce tutorial to its own directory, that way we would not clutter the `examples` directory with multiple shared files as we add additional tutorials and demos in there and we will keep it organized.

## Related Tickets & Documents

Closes #82 

## Added to documentation?

- [x] 📜 readme
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by chuck-alt-delete — APPROVED** [review]
Is there any chance we could remove zookeeper? Extra bloat not needed since Kafka went zookeeperless. It’s fine if not

**Comment by bobbyiliev** [comment]
does not seem to work If I try to use the latest `confluentinc/cp-kafka` image:

```
dc logs -f kafka
kafka  | ===> User
kafka  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka  | ===> Configuring ...
kafka  | KAFKA_ZOOKEEPER_CONNECT is required.
kafka  | Command [/usr/local/bin/dub ensure KAFKA_ZOOKEEPER_CONNECT] FAILED !
```

**Comment by chuck-alt-delete** [comment]
@bobbyiliev here is a good reference: https://github.com/confluentinc/learn-kafka-kraft

**Comment by larsenpanda** [comment]
Shameless plug to stand up Redpanda as the Kafka, it's way better in docker.

**Comment by bobbyiliev** [comment]
Thank you for the suggestion @larsenpanda! Just updated the demo!

@chuck-alt-delete that whole setup seems a bit funky for a simple example, we remove 4 lines of zookeeper definition to add 10+ lines of Kafka configuration and a volume for the `update_run.sh` script which seems to add more bloat than just starting zookeeper?

**Pull request merged**
