### PR TITLE
Switch tests to redpanda

### LINKED ISSUE #87: Improve integration tests
- [ ] Use redpanda docker image like we do in the docker example to easily remove zookeeper
- [ ] Use [path filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to only run tests when relevant files change. I.e. don't run tests for an update to readme.md.
- [ ] Is there a way to pre-cache docker images on the runner so it isn't pulling every time? I found [this example](https://mmeendez8.github.io/2021/07/19/new-docker-cache-is-out.html) but I haven't looked at it deeply

### PR DESCRIPTION
**Pull request by bobbyiliev**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Switching the Kafka + CSR + Zookeeper containers to Redpanda.
Adding a path ignore for the `.md`, `.txt` files, and `examples` directory.

Not 100% sure if there will be any actual benefits of switching to the image caching suggestion as we only have the Redpanda image that will be pulled and we need to make sure that the datagen image is built fresh on every run to prevent some weird results. Open to suggestions!

## Related Tickets & Documents

Closes #87 

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by chuck-alt-delete** [comment]
Looking at the integration test results, it seems like several of these tests are actually failing. Things like

> 404 subject Products-value doesn’t exist

There’s also a failure on tests/schema2.sql that I think is a separate bug.

Regardless, these tests should show fail. Curious why they aren’t.

**Review by chuck-alt-delete — CHANGES_REQUESTED** [review]
Integration tests show pass, but if you look at the details, they are actually failing

**Comment by chuck-alt-delete** [comment]
Ah yes, here’s another place where we should exit 1:

https://github.com/MaterializeInc/datagen/blob/main/datagen.ts#L104

**Comment by bobbyiliev** [comment]
Good catch @chuck-alt-delete! I've added those `exit 1` changes and fixed the mismatching prefixes in the tests!

**Review by chuck-alt-delete — CHANGES_REQUESTED** [review]
Just need to add exit 1 here: https://github.com/MaterializeInc/datagen/blob/main/datagen.ts#L104

and remove schema2.sql from the tests (that’s a bug we should look into separately — it has to do with using multiple columns as a primary key)

**Comment by bobbyiliev** [comment]
> Just need to add exit 1 here: https://github.com/MaterializeInc/datagen/blob/main/datagen.ts#L104
> 
> and remove schema2.sql from the tests (that’s a bug we should look into separately — it has to do with using multiple columns as a primary key)

Had to update the Parse schema process exit [here](https://github.com/MaterializeInc/datagen/pull/89/files#diff-c9b82968a363c089f93009ac24d828a38a80cbef2d607acf9cd21cd9fe9c4d88R104) as well so that those problems would cause an error.

Also disabling the SQL to avro tests as there is a bug with the naming convention of the schemas, eg the schemas can not be registered when there is a dot in the name name:

```
| ✖  Failed to register schema.  ResponseError: Confluent_Schema_Registry - name doesn't match namespace {"name":"ecommerce.products","type":"record","fields":[{"name":"id","type":"int"},{"name":"name","type":"string"},{"name":"merchant_id","type":"int"},{"name":"price","type":"int"},{"name":"status","type":"boolean"},{"name":"created_at","type":"string"}],"namespace":"com.materialize"}
```

The error message indicates that the name of the schema, "ecommerce.products", does not match the namespace specified in the schema, "com.materialize". In the Confluent Schema Registry, the name of the schema should include the namespace, so the correct name for this schema would be "com.materialize.ecommerce.products" or we should not allow dots to be used in the schema names instead.

We should open a separate issue for this.

**Review by chuck-alt-delete — APPROVED** [review]
Sweet! Nice work fixing up these tests!

**Pull request merged**
