### PR TITLE
Add Relational data

### LINKED ISSUE #1: Feature: Add support for generating relational data
An experimental JSON relational option has been added. We need to add the same for SQL and AVRO schemas.

This adds some very basic relational functionality for JSON schemas. You can specify the PK and the FK in the schema eg:
```json
[
    {
        "_meta": {
            "topic": "mz_datagen_users",
            "key": "id"
        },
        "id": "datatype.uuid",
        "name": "internet.userName",
        "email": "internet.exampleEmail",
        "phone": "phone.imei",
        "website": "internet.domainName",
        "city": "address.city",
        "company": "company.name"
    },
    {
        "_meta": {
            "topic": "mz_datagen_posts",
            "foreignKey": "user_id",
            "key": "id"
        },
        "id": "datatype.uuid",
        "user_id": "datatype.uuid",
        "title": "lorem.sentence",
        "body": "lorem.paragraph"
    },
]
```
A unique ID will be generated and used for the `users.id` and `posts.user_id`

### PR DESCRIPTION
**Pull request by chuck-alt-delete**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Related Tickets & Documents

closes #1 

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by chuck-alt-delete** [comment]
work in progress. Trying to precompute key spaces and use those during record generation.

**Comment by chuck-alt-delete** [comment]
May be helpful: https://github.com/faker-js/faker/issues/1856#issuecomment-1435955916

**Comment by chuck-alt-delete** [comment]
The more I think about it, the more I feel we should parse the schema file into one big object (rather than a list] and have a preprocessing step for things like registering schema and generating a relational keyspace. Then instead of iterating over the schema file list to produce records, we would create multiple records at once to ensure the key relationships.

**Comment by chuck-alt-delete** [comment]
There's a bug parsing avsc files I think I picked up from main on rebase (this PR doesn't touch parsing avsc files). If reviewers agree, I think we can merge this to main and tackle the avsc bug separately.

I tested this with json and sql schema files -> confluent cloud with avro schema -> materialize, where I did some sample joins and it's looking good! For example:

```sql
SELECT
	p.title
FROM
	posts AS p JOIN users AS u ON u.id = p.user_id
WHERE
	u.id = '1406d66f-6423-45ce-bb22-61da6b06a8fa';
```

```
-[ RECORD 1 ]------------------------------------------------------------------
title | Libero labore corporis nisi.
-[ RECORD 2 ]------------------------------------------------------------------
title | Voluptate aliquam natus deleniti distinctio perspiciatis culpa ducimus.
```

Meaningful join results!

**Review by bobbyiliev — APPROVED** [review]
LGTM! 🔥 

I've got a fix for the failing tests and will push it in a second!

**Pull request merged**
