### PR TITLE
Convert to TypeScript

### LINKED ISSUE #60: Feature: Consider migrating to typescript
### Is your feature request related to a problem? Please describe.

I find javascript very difficult to write and maintain. I need types and access modifiers to formulate my thoughts in code. 

### Describe the solution you'd like

I want to open the discussion of migrating to typescript, and I'd like to hear everyone's thoughts for and against it.

### PR DESCRIPTION
**Pull request by bobbyiliev**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Initial conversation to TS.

## Related Tickets & Documents

Closes #60 

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by sjwiesman** [comment]
Wow you are fast. Why is this marked in progress? We don't need to make everything idiomatic in this PR. Getting the build system updated is most important. Everything else can be piecemeal.

**Comment by sjwiesman** [comment]
If this compiles and works, I'm inclined to say merge and increment.

**Comment by bobbyiliev** [comment]
> Wow you are fast. Why is this marked in progress? We don't need to make everything idiomatic in this PR. Getting the build system updated is most important. Everything else can be piecemeal.

There is one bug that the integration tests caught:

```
| ✔  Schema registered!  Subject: mz_datagen_comments-value, ID: 4
| 
| /app/node_modules/@kafkajs/confluent-schema-registry/dist/SchemaRegistry.js:153
|             throw new errors_1.ConfluentSchemaRegistryArgumentError(`Invalid registryId: ${JSON.stringify(registryId)}`);
|                   ^
| 
| ConfluentSchemaRegistryArgumentError: Invalid registryId: undefined
|     at SchemaRegistry.encode (/app/node_modules/@kafkajs/confluent-schema-registry/dist/SchemaRegistry.js:153:19)
|     at file:///app/dist/src/schemas/schemaRegistry.js:65:44
```

Wanted to fix that first before merging

**Comment by chuck-alt-delete** [comment]
That but and a couple of others are fixed in my open PR. Maybe we can merge that one first?

**Comment by bobbyiliev** [comment]
> That bug (I think) and a couple of others are fixed in my open PR. Maybe we can merge that one first?

Ok sounds good, let's merge #62 and then I'll rebase and go from there!

**Comment by chuck-alt-delete** [comment]
Ok done!

**Comment by bobbyiliev** [comment]
Just pushed the changes from main. Seems like we are still hitting that error:

```
| ✔  Registering Avro schema...  
| 
| file:///app/dist/src/schemas/schemaRegistry.js:17
|         schema.name = `name${i++}`;
|                     ^
| 
| TypeError: Cannot create property 'name' on string 'string'
```

**Comment by chuck-alt-delete** [comment]
That looks like a new error

**Comment by bobbyiliev** [comment]
> That looks like a new error

Ah yes, no that was actually the initial error, before I started debugging and trying out stuff

**Review by chuck-alt-delete — APPROVED** [review]

**Pull request merged**
